#!/usr/bin/env node

/**
 * vault-init.mjs — Initialize the Obsidian memory vault structure
 *
 * Usage:
 *   node vault-init.mjs --vault-path /path/to/obsidian/vault
 *   node vault-init.mjs --vault-path /path/to/vault --memory-folder my-memories --language en
 *
 * Creates:
 *   - .vault-config.json in current directory AND home directory
 *   - Folder structure inside the vault
 *   - A welcome note explaining the system
 */

import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join, resolve } from "path";

function parseArgs(args) {
  const parsed = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith("--")) {
      const key = args[i].slice(2);
      const val = args[i + 1] && !args[i + 1].startsWith("--") ? args[++i] : true;
      parsed[key] = val;
    }
  }
  return parsed;
}

const args = parseArgs(process.argv.slice(2));

if (!args["vault-path"]) {
  console.error("ERROR: --vault-path is required");
  console.error("Usage: node vault-init.mjs --vault-path /path/to/obsidian/vault");
  process.exit(1);
}

const vaultPath = resolve(args["vault-path"]);
const memoryFolder = args["memory-folder"] || "claude-memory";
const language = args.language || "pt-BR";
const autoSave = args["auto-save"] === "true";

if (!existsSync(vaultPath)) {
  console.error(`ERROR: Vault path does not exist: ${vaultPath}`);
  console.error("Create the vault in Obsidian first, then run this script.");
  process.exit(1);
}

// --- Create config ---

const config = {
  vault_path: vaultPath,
  memory_folder: memoryFolder,
  auto_save: autoSave,
  language,
};

const configJson = JSON.stringify(config, null, 2);

// Save to current directory
writeFileSync(join(process.cwd(), ".vault-config.json"), configJson, "utf-8");

// Save to home directory as fallback
const homeConfig = join(process.env.HOME || "~", ".vault-config.json");
writeFileSync(homeConfig, configJson, "utf-8");

// --- Create folder structure ---

const memoryPath = join(vaultPath, memoryFolder);
const folders = [
  "decisions",
  "learnings",
  "contexts",
  "conversations",
  "entities",
  "snippets",
  "_indexes",
];

for (const folder of folders) {
  mkdirSync(join(memoryPath, folder), { recursive: true });
}

// --- Create welcome note ---

function isoNow() {
  return new Date().toISOString().replace("Z", "-03:00");
}

const now = isoNow();
const welcomeNote = `---
type: context
title: "Claude Memory Vault — Guia de Uso"
created: ${now}
updated: ${now}
tags:
  - claude-memory
  - meta
  - status/active
aliases:
  - "Como funciona a memória do Claude"
confidence: high
source: manual
---

# Claude Memory Vault — Guia de Uso

Este vault é a **memória externa do Claude Code**. Cada conversa significativa
produz notas atômicas e interconectadas que o Claude pode consultar em sessões futuras.

## Estrutura de Pastas

| Pasta | Conteúdo |
|-------|----------|
| \`decisions/\` | Decisões de arquitetura, design, tecnologia |
| \`learnings/\` | Bugs resolvidos, gotchas, descobertas |
| \`contexts/\` | Estado atual de projetos e ambientes |
| \`conversations/\` | Resumos de sessões com o Claude |
| \`entities/\` | Ferramentas, libs, serviços, pessoas |
| \`snippets/\` | Código reutilizável, queries, comandos |
| \`_indexes/\` | MOCs (Maps of Content) auto-gerados |

## Como Funciona

1. **Wikilinks** conectam todas as notas entre si, formando um grafo de conhecimento
2. **Tags hierárquicas** (\`#project/nome\`, \`#topic/area\`) permitem busca facetada
3. **Frontmatter YAML** em cada nota permite filtrar por tipo, data, confiança
4. **MOCs** são índices auto-gerados que agrupam notas por projeto ou tópico

## Comandos para o Claude Code

- \`"salvar no vault"\` — persiste a conversa atual
- \`"o que decidimos sobre X?"\` — busca decisões
- \`"lembrar isso"\` — salva um item específico
- \`"stats do vault"\` — mostra estatísticas
- \`"reindexar vault"\` — reconstrói os MOCs

## Graph View

Abra o **Graph View** do Obsidian para visualizar a rede de conhecimento.
Filtre por \`tag:claude-memory\` para ver apenas as notas do Claude.

## Dica

Quanto mais você usa, mais interconectado e útil o vault fica.
O Claude pode "seguir" wikilinks para reunir contexto completo sobre qualquer tópico.
`;

const welcomePath = join(memoryPath, "contexts", "vault-guia-de-uso.md");
if (!existsSync(welcomePath)) {
  writeFileSync(welcomePath, welcomeNote, "utf-8");
}

// --- Create .gitignore for vault (optional) ---

const gitignorePath = join(memoryPath, ".gitignore");
if (!existsSync(gitignorePath)) {
  writeFileSync(gitignorePath, "# Generated by claude-memory\n# Add patterns here if needed\n", "utf-8");
}

// --- Output ---

console.log(JSON.stringify({
  action: "initialized",
  vault_path: vaultPath,
  memory_path: memoryPath,
  config_paths: [
    join(process.cwd(), ".vault-config.json"),
    homeConfig,
  ],
  folders_created: folders.map((f) => join(memoryFolder, f)),
  welcome_note: welcomePath,
  language,
  auto_save: autoSave,
}, null, 2));
